Repository Aviles17/Bot_Supertrend, pull requests merged in 2024-09, with the labels that each got.

#37 Develop -> fix: Extracción de datos a traves del API de forma correcta y modularidad
  scripts/Heartbeat_server.cpp
  scripts/ST_Indicators.py
  scripts/start-VM.sh
  src/Bot_SuperTrend.py
  tests/util_tests.py
Labels: bug, enhancement

#38 Develop
  scripts/ST_Indicators.py
  scripts/start-VM.sh
  tests/posicion_tests.py
  tests/util_tests.py
Labels: bug, enhancement

#39 hotfix: Añadir DOTUSDT y eliminar prints
  scripts/ST_Indicators.py
  src/Bot_SuperTrend.py
Labels: enhancement

#40 Hotfix: Polaridad modificada por recuperación de ordenes, mas información al failsafe y mas margen
  scripts/Heartbeat_server.cpp
  scripts/ST_Indicators.py
  src/Bot_SuperTrend.py
  src/Posicion.py
Labels: bug

#41 Develop
  scripts/ST_Indicators.py
  src/Bot_SuperTrend.py
Labels: bug

#42 Generalizar función de calculo de la Supertrend y cambio de estrategia
  scripts/ST_Indicators.py
  src/Bot_SuperTrend.py
  tests/util_tests.py
Labels: enhancement
