Repository Aviles17/Bot_Supertrend, pull requests merged in 2024-03, with the labels that each got.

#7 Migración exitosa a version 5 del API de Bybit
  requirements.txt
  scripts/ST_Indicators.py
  src/Bot_SuperTrend.py
  src/Posicion.py
  tests/posicion_tests.py
  tests/util_tests.py
Labels: enhancement

#8 Hotfix DEMA800 y revisión en ventana de tiempo
  scripts/ST_Indicators.py
  src/Bot_SuperTrend.py
Labels: bug

#10 Created LICENSE
  LICENSE
Labels: documentation

#9 Update README.md
  README.md
Labels: documentation

#11 Error de sintaxis en la linea 172 solucionado
  scripts/ST_Indicators.py
Labels: bug

#12 fix: Cambios en el calculo del DEMA800 para mas precisión
  scripts/ST_Indicators.py
Labels: bug

#13 Hotfix funcionalidades de Stoploss-Reached y Revision de arreglo
  scripts/ST_Indicators.py
  src/Posicion.py
Labels: bug, enhancement

#14 Tamaño de ordenes solucionado y pares actualizacos [xrpusdt, oneusdt]
  config/Credenciales_template.py
  scripts/ST_Indicators.py
  src/Bot_SuperTrend.py
  src/Posicion.py
  tests/posicion_tests.py
Labels: enhancement

#16 HalfSell solucionado para poder manejar solamente numeros enteros
  src/Posicion.py
Labels: bug

#17 Correción de tamaño de ordenes
  scripts/ST_Indicators.py
Labels: bug, documentation
